apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  selector:
    app.kubernetes.io/name: vproapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: vproapp-port