apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector:
    app.kubernetes.io/name: vpromc
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 11211
      targetPort: vpromc-port