apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  selector:
    app.kubernetes.io/name: vpromq01
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15672
      targetPort: vpromq01-port