apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
    app.kubernetes.io/name: vprodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: vprodb-port